In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import pairwise_distances
import numpy as np

text = ["wookie stormtrooper",
        "wookie wookie wookie stormtrooper stormtrooper stormtrooper",
        "harry potter"]

In [2]:
vect = CountVectorizer()
data = vect.fit_transform(text).todense()

In [3]:
vect.get_feature_names()

[u'harry', u'potter', u'stormtrooper', u'wookie']

In [4]:
data

matrix([[0, 0, 1, 1],
        [0, 0, 3, 3],
        [1, 1, 0, 0]])

In [5]:
pairwise_distances(data, metric='euclidean').round(3)

array([[ 0.   ,  2.828,  2.   ],
       [ 2.828,  0.   ,  4.472],
       [ 2.   ,  4.472,  0.   ]])

In [6]:
pairwise_distances(data, metric='cosine')

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  1.,  0.]])

In [7]:
1 - pairwise_distances(data - data.mean(axis=1), metric='cosine')

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.]])

In [8]:
np.corrcoef(data)

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.]])