In [19]:
import numpy as np
import matplotlib.pyplot as plt
from collections import OrderedDict
% matplotlib inline
from copy import deepcopy
points = np.random.rand(100,2)

In [2]:
def distance(A, B):
    squares = [(a - b) ** 2 for a, b in zip(A, B)]
    return sum(squares) ** 0.5

The centroid is just the average of all points in that cluster:

In [11]:
np.random.rand(k,2)

array([[ 0.01701927,  0.90027231]])

In [3]:
def updateCentroids(points,centroids,clusters):
    initial = np.random.rand(len(centroids), 2)
    

SyntaxError: unexpected EOF while parsing (<ipython-input-3-ba774dd58d1d>, line 1)

For each point, find the distance to all centroids and assign it to the closest one. The distance function is already available above.

In [51]:
centroids
centroids = deepcopy(points[:2])
clusters = np.zeros(len(points))

In [53]:
clusters[2] = 1

In [54]:
clusters

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [55]:
for pt in range(len(points)):
    print pt

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [62]:
d = OrderedDict()

# d = {[0.5, .05]: [1, 2, 3]}
#     {[0.5, .05]: [4, 5, 6]}
#     {[0.5, .05]: [7, 8, 9]}
    
# [1, 2, 3]
# [4, 5, 6]

def assignPoints(points,centroids,clusters):
    for p in points:
        pt = tuple(p)
        for cent in centroids:
            if pt not in d:
                d[pt] = [distance(pt, cent)]
            else:
                d[pt].append(distance(pt,cent))
    for pt in range(len(points)):
            clusters[pt] = d.values()[pt].index(min(d.values()[pt]))
    return clusters

In [65]:
assignPoints(points, centroids, clusters)

array([ 0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.])

We have a points array of length 100. We create "clusters" to be a list of the same length. We can use it to assign each point a cluster number. We will have k "centroids" and we just assign the first k points to be the centroids.

In [ ]:
def KMeans(points,k=3):
    clusters = np.zeros(len(points))
    centroids = deepcopy(points[:k])
    while assignPoints(points,centroids,clusters):
        updateCentroids(points,centroids,clusters)
    plt.scatter([p[0] for p in points],[p[1] for p in points],c=clusters)
    plt.show()


In [ ]:
KMeans(3)